@ECHO OFF
SET LOCAL
SET CHOICE=1
SET NEW_DATASET=drift
SET K=10
SET POINTS=39000
SET EPOCH=3
SET VAR=4
SET FEATURES=10
SET VPER=0
SET ERROR= 0.1
SET WIN_SIZE=2000
SET WIN_STEP=1
SET TEST=False
SET DEBUG=False
SET IN_FILE=io_files/inputs/drift
SET MED_NAME=k10_ft10_e0.1_win2000_ep3
SET START_NAME=io_files/gm/drift/window/

python main.py %CHOICE% %NEW_DATASET% %K% %POINTS% %EPOCH% %VAR% %FEATURES% %VPER% %ERROR% %WIN_SIZE% %WIN_STEP% %TEST% %DEBUG% %IN_FILE% %MED_NAME% %START_NAME%

PAUSE